== Instructions for deploying Data Science Object Detection workshop

=== Request RHPDS cluster

OpenShift 4.12

=== Install Red Hat OpenShift Data Science 

via RHODS operator

=== Limit Ranges

Modify limitranges set on notebook project: 8Gi conatiner and 14Gi Pod memory

[source,bash]
----
kind: LimitRange
apiVersion: v1
metadata:
  name: rhods-notebooks-core-resource-limits
  namespace: rhods-notebooks
spec:
  limits:
    - type: Container
      max:
        cpu: '4'
        memory: 8Gi
      default:
        cpu: 500m
        memory: 1536Mi
      defaultRequest:
        cpu: 50m
        memory: 256Mi
    - type: Pod
      max:
        cpu: '4'
        memory: 14Gi
----

=== Create users and projects

Merge existing htpasswd file with supplied, this create a user community of userN 1..N. 
Drop down into the htpasswd directory where the password updater is located.

[source,bash]
----
cd htpasswd
./updatehtpasswd.sh
----

Create projects for each user in their name

[source,bash]
----
./createProject.sh <cluster API URL>
----

===Install portal tool for user mapping

Come up a directory level and create ods-portal project

[source,bash]
----
cd ..
oc new-project ods-portal
----

Install user selection tool (redis/portal)

[source,bash]
----
oc apply -f redis-deploy.yaml
----

Update local route to rhods notebooks

[source,bash]
----
oc apply -f portal-deploy.yaml
----

Update the long and ugly LAB_MODULE_URLS environment variable in the portal application. This single string
contains both the lab guide and RHODS dashboard URL. Once you know the route of the 
rhods ods dashboard edit the second URL value. It will look a little like this: *https://rhods-dashboard-redhat-ods-applications.apps.cluster...*

=== Scale cluster

Extend cluster nodes according to expected load. 25 users approx 6 worker nodes

=== Test
